package evaluacion;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.media.Buffer;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;

/**
 * Ventana interna de reproducción de video.
 *
 * @author German Martinez Maldonado
 */
public class VentInternaReprVide extends javax.swing.JInternalFrame {

    private Player player;

    /**
     * Obtiene una instancia de reproductor de video.
     *
     * @param f El archivo de video que se intenta reproducir.
     * @return Si el archivo se puede reproducir se devuelve un reproductor que
     * reproduzca ese archivo, en caso contrario se devolverá "null".
     */
    public static VentInternaReprVide getInstance(File f) {
        VentInternaReprVide ventana = new VentInternaReprVide(f);

        if (ventana.player == null) {
            return null;
        } else {
            return ventana;
        }
    }

    /**
     * Constructor de la ventana interna de reproducción de video.
     *
     * @param f El archivo de video que se intenta reproducir.
     */
    private VentInternaReprVide(File f) {
        initComponents();

        play(f);
    }

    /**
     * Crea el reproductor de video (si es posible) e inicia la reproducción.
     *
     * @param f El archivo de video que se intenta reproducir.
     */
    public void play(File f) {
        try {
            URL url = f.toURI().toURL();

            MediaLocator ml = new MediaLocator(url);
            player = Manager.createRealizedPlayer(ml);

            Component areaVisual = player.getVisualComponent();
            if (areaVisual != null) {
                add("Center", areaVisual);
            }

            Component panelControl = player.getControlPanelComponent();
            if (panelControl != null) {
                add("South", panelControl);
            }

            setTitle(f.getName());

            player.start();
        } catch (IOException ioe) {
            player = null;
            System.err.println("Error: Fallo de entrada/salida relacionado con el archivo de video a reproducir. " + ioe.getMessage());
        } catch (NoPlayerException npe) {
            player = null;
            System.err.println("Error: No se ha podido encontrar un reproductor para el video a reproducir. " + npe.getMessage());
        } catch (CannotRealizeException cre) {
            player = null;
            System.err.println("Error: Fallo cuando se intentaba realizar el reproductor de video. " + cre.getMessage());
        }
    }

    /**
     * Captura la imagen actual en el video que se está reproduciendo.
     *
     * @return Imagen capturada.
     */
    public BufferedImage getFrame() {
        FrameGrabbingControl fgc;
        String claseCtr = "javax.media.control.FrameGrabbingControl";
        fgc = (FrameGrabbingControl) player.getControl(claseCtr);
        Buffer bufferFrame = fgc.grabFrame();
        BufferToImage bti;
        bti = new BufferToImage((VideoFormat) bufferFrame.getFormat());
        Image img = bti.createImage(bufferFrame);
        return (BufferedImage) img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(320, 240));
        setPreferredSize(new java.awt.Dimension(640, 480));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                VentanaInternaReproduccionVideoClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción correspondiente a cerrar la ventana de reproducción. Cierra el
     * reproductor de video.
     *
     * @param evt Evento que produce el inicio de la acción (cierre de ventana
     * interna).
     */
    private void VentanaInternaReproduccionVideoClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_VentanaInternaReproduccionVideoClosing
        player.close();
    }//GEN-LAST:event_VentanaInternaReproduccionVideoClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
